let ResultCategory = {
  JOBS_INDEED: 'RESULTS_CATEGORY_JOBS',
  EVENTS_EVENTBRITE: 'RESULTS_CATEGORY_EVENTS',
  COURSES_UDEMY: 'RESULTS_CATEGORY_COURSES',
  GIGS_FREELANCER: 'RESULTS_CATEGORY_GIGS',
};

export default ResultCategory;
